baseURL = "https://vincentvandercruyssen.github.io/kunstkaai/"
languageCode = 'nl'
title = 'Kunstkaai'

disableKinds = ["RSS", "taxonomy", "term"]

[params.sectionNames]
  audiovisueel_atelier = "Audiovisueel atelier"
  data = "Datamanagement"
  digitaal = "Digitaal atelier"
  grafisch_atelier = "Grafisch atelier"
  typo = "Typografische Vormgeving"
  web = "Webontwikkeling"
  weborientatie = "WeboriÃ«ntatie"
  doelen = "Doelen GO! Navigator"

[params]
  dateFormat = "2006-01-02"
  dateFormatISO = "2006-01-02"

[imaging]
  quality = 90
  resampleFilter = 'Lanczos'

[build]
  cleanDestinationDir = true

[markup]
[markup.highlight]
  style = "rose-pine-moon"